#!/usr/bin/env python3
"""Turns data/lines.txt into src/PbaCatalog.cpp: the lines the bots say, built into the module."""
import os, zlib

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
rows = []
with open(os.path.join(root, 'data', 'lines.txt'), encoding='utf-8') as source:
    for number, line in enumerate(source, 1):
        line = line.rstrip('\n')
        if not line or line.startswith('#'):
            continue
        parts = line.split('|')
        if len(parts) != 3:
            raise SystemExit('line %d: expected personality|occasion|text' % number)
        personality, occasion, text = (part.strip() for part in parts)
        if not text or len(text) > 255 or any(ord(c) < 32 or ord(c) > 126 for c in text):
            raise SystemExit('line %d: text must be 1 to 255 characters of plain ASCII' % number)
        rows.append((personality, occasion, text))

def literal(text):
    return '"' + text.replace('\\', '\\\\').replace('"', '\\"').replace('??', '?\\?') + '"'

version = zlib.crc32('\n'.join('|'.join(row) for row in rows).encode()) or 1
with open(os.path.join(root, 'src', 'PbaCatalog.cpp'), 'w', encoding='utf-8', newline='\n') as out:
    out.write('// Generated by tools/make_catalog.py from data/lines.txt. Do not edit: change the text file and run the tool.\n\n')
    out.write('#include "Pba.h"\n\nnamespace pba\n{\n')
    out.write('    uint32 const CatalogVersion = %du;\n\n' % version)
    out.write('    CatalogLine const Catalog[] =\n    {\n')
    for row in rows:
        out.write('        { %s, %s, %s },\n' % tuple(literal(part) for part in row))
    out.write('    };\n\n    size_t const CatalogSize = sizeof(Catalog) / sizeof(Catalog[0]);\n}\n')
print('%d lines, version %d' % (len(rows), version))
